import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,10,100)
y=np.sin(x)
fig,ax=plt.subplots()
ax.plot(x,y,color='red',linestyle='-',linewidth=2)
ax.set_title('Sine Wave')
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.grid(True,linestyle='--',color='gray',alpha=0.5)
ax.set_xticks(np.linspace(0,10,11))
ax.set_xticklabels(['0','1','2','3','4','5','6','7','8','9','10'])
ax.set_yticks(np.linspace(-1,1,11))
ax.tick_params(axis='both',labelsize=10)
ax.legend(['Sine Wave'],loc='upper right')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['bottom'].set_linewidth(1.5)
ax.spines['left'].set_position(('outward',10))
plt.show()